# belum dikonfigurasi semua
# version: "3.9"

# services:
#   db:
#     container_name: mongo
#     image: mongo:4 
#     ports: 
#       - 8080:8080

version: '3.9'
services:
  db:
    image: mongo:7.0.5
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: app-server
    restart: always
    ports:
      - 5001:5001
    depends_on:
      - db

volumes:
  mongo-data: